sudo: required
dist: xenial
language: C

install:
- ./tools/install_depencies_travis.sh

script:
- export LD_LIBRARY_PATH="/usr/lib/:/usr/lib/x86_64-linux-gnu/:$LD_LIBRARY_PATH"
- export PKG_CONFIG_PATH="/usr/lib/pkgconfig/:/usr/lib/x86_64-linux-gnu/pkgconfig/:$PKG_CONFIG_PATH"
- make
